### ISSUE TITLE
Get api for user properties?

### ISSUE THREAD

**Issue by kastriotkastrati** [OneSignal/onesignal-cpp-api#7]
### How can we help?

Hello, I'm just wondering why is there no GET route in the API to get the user properties?

https://documenter.getpostman.com/view/16845437/TzscpSWK
I need to get the user properties and this seems like a basic need, unless I am missing something.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @kastriotkastrati, thanks for the question! Perhaps what you need is a [Player/Device](https://documentation.onesignal.com/reference/view-device) model. You can get it calling 
```cpp
// Send a get request
const auto getResponse = api->getPlayer(APP_ID, "<PLAYER_ID>", boost::none);
```
Our **user**/**player**/**device** terminology might be a bit confusing but we are currently working on improving this situation drastically. Please let me know if this does not help!

**Comment by kastriotkastrati** [comment]
Hey @kesheshyan, thank you for your answer. I want to discuss something further, however, I'll close the issue now.

My use case concerns user tags. Through the API, I am able to set user tags with external_user_id, which represents an actual id of the user on my db, all very convenient so far. 

The problem arises when I want to get the current tags of this user, herein, I need to make a query with player_id, which I don't have. To me, it feels inconsistent to set/update user tags with external_user_id while getting tags is only available with player_id param. I've found ways to work around this, but it just seems off a bit.

As far as I know, player tags are per external_user_id, not per platform (player_id) right? In which case it would be even less practical to have them there.
